# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            luke reding
tagline:          'data scienists'
description:      'statistics :: data analysis :: programming'
url:              lukereding.github.io

author:
  name:           'Luke Reding'
  url:            lukereding.github.io
baseurl:          /
paginate:         1

# Custom vars
last updated:   03 Sept 2016

github:
  repo:           https://github.com/lukereding/

plugins: [jekyll-paginate]
future: true
